models/__init__.py
from .post import Post

__all__ = [
    "Post",
]

models/database.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

__all__ = [
    "db",
]

models/post.py
from werkzeug.exceptions import NotFound
from sqlalchemy import Column, Integer, String, Boolean, Text, ForeignKey
from models.database import db
from sqlalchemy.orm import relationship

class User(db.Model):
    id = Column(Integer, primary_key=True)
    username = Column(String(30), nullable=False)

    posts = relationship("Post", back_populates="user")

class Post(db.Model):
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey(User.id), nullable=False)
    title = Column(String(50), nullable=False)
    text = Column(Text, nullable=False)
    is_published = Column(Boolean, nullable=False, default=False)
    deleted = Column(Boolean, nullable=False, default=False, server_default="0")

    user = relationship(User, back_populates="posts")

    @classmethod
    def get_post_by_id(cls, post_id, deleted=False):
        post = cls.query.filter_by(deleted=deleted, id=post_id).one_or_none()
        if post is None:
            raise NotFound(f"Product #{post_id} not found!")
        return post

app.py
from flask import Flask, request, render_template
from flask_migrate import Migrate

import config
from views.posts import post_app
from models.database import db

app = Flask(__name__)
app.register_blueprint(post_app, url_prefix="/posts")

app.config.update(
    SQLALCHEMY_DATABASE_URI=config.SQLALCHEMY_DATABASE_URI,
    SQLALCHEMY_TRACK_MODIFICATIONS=False,
)

db.init_app(app)
Migrate(app, db, compare_type=True)

@app.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        return "Hello POST!!"
    name = request.args.get("name") or "World"
    return render_template("index.html", name=name)

@app.cli.command('init-db', with_appcontext=True)
def initialize_db():
    """
    Create initial db
    # not use due to Flask-Migrate
    """
    print("Do init db")
    db.create_all()
    print("init db done")

if __name__ == "__main__":
    app.run(
        host="localhost",
        port=5000,
        debug=True
    )

main.py
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, Text, Boolean, ForeignKey, select
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, Session

engine = create_engine("sqlite:///app.db")
metadata = MetaData(bind=engine)
Base = declarative_base(bind=engine)

posts_tags_m2m_table = Table(
    "posts_tags",
    Base.metadata,
    Column("post_id", Integer, ForeignKey("posts.id"), primary_key=True),
    Column("tag_id", Integer, ForeignKey("tags.id"), primary_key=True),
)


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    username = Column(String(30), nullable=False)

    posts = relationship("Post", back_populates="user")
    comments = relationship("Comment", back_populates="user")

    def __str__(self):
        return str(self.username)

    def __repr__(self):
        return str(self)


class Post(Base):
    __tablename__ = "posts"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey(User.id), nullable=False)
    title = Column(String(50), nullable=False)
    text = Column(Text, nullable=False)
    is_published = Column(Boolean, nullable=False, default=False)

    user = relationship(User, back_populates="posts")
    tags = relationship("Tag", secondary=posts_tags_m2m_table, back_populates="posts")
    comments = relationship("Comment", back_populates="posts")

    def __str__(self):
        return str(self.title)

    def __repr__(self):
        return str(self)


class Tag(Base):
    __tablename__ = "tags"

    id = Column(Integer, primary_key=True)
    name = Column(String(16), nullable=False, unique=True)

    posts = relationship(Post, secondary=posts_tags_m2m_table, back_populates="tags")

    def __str__(self):
        return str(self.name)

    def __repr__(self):
        return str(self)


class Comment(Base):
    __tablename__ = "comments"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey(User.id), nullable=False)
    id_post = Column(Integer, ForeignKey(Post.id),nullable=False)
    text = Column(Text, nullable=False)
    parent_comment = Column(Integer, nullable=True)

    user = relationship(User, back_populates="comments")
    posts = relationship(Post, back_populates="comments")

    def __str__(self):
        return str(self.text)

    def __repr__(self):
        return str(self)

def create_users_and_posts_and_tags_and_comments():
    session = Session()

    user1 = User(username="Anna")
    session.add(user1)
    user2 = User(username="Mark")
    session.add(user2)
    user3 = User(username="Olga")
    session.add(user3)

    session.flush()

    post1 = Post(user_id=user1.id, title="Strengthening exercises",
                 text="Strengthening activities focus on building up or maintaining strength in your major muscle"
                      " groups – for example, your arms and legs. Doing exercises to improve strength is important"
                      " throughout life. ")
    post2 = Post(user_id=user1.id, title="Aerobic exercise",
                 text="Aerobic exercise is any type of continuous activity that works your heart, lungs and muscles. "
                      "Examples include brisk walking, cycling, running, swimming, dancing and football.")
    post3 = Post(user_id=user3.id, title="Eating and exercise: 5 tips to maximize your workouts",
                 text="1. Eat a healthy breakfast, 2. Watch the portion size, 3. Snack well, 4. Eat after you exercise "
                      "5. Drink up")

    session.add(post1)
    session.add(post2)
    session.add(post3)

    tag_news_1 = Tag(name="exercise")
    tag_news_2 = Tag(name="aerobic")
    tag_news_3 = Tag(name="strengthening")

    session.add(tag_news_1)
    session.add(tag_news_2)
    session.add(tag_news_3)

    session.flush()

    post1.tags.extend((tag_news_1, tag_news_3))
    post2.tags.extend((tag_news_1, tag_news_2))
    post3.tags.extend((tag_news_1, ))

    comment1 = Comment(user_id=user2.id, id_post=post1.id,
                       text='Swimming is a great form of exercise for people of all ages and abilities.')

    comment2 = Comment(user_id=user1.id, id_post=post1.id,
                       text=' It’s also a great choice if you have any problems with your joints, such as arthritis.',
                       parent_comment=comment1.id)

    session.add(comment1)
    session.add(comment2)

    session.commit()

    session.close()

def get_posts_by_id_user(user):
    session = Session()
    result = session.query(Post).filter_by(user_id=user)

    print('Posts by user', user)
    for row in result:
        print('Title: ', row.title, ' Text: ', row.text)

def get_posts_by_tag(tag):
    session = Session()
    result = session.query(Post).join(posts_tags_m2m_table).filter(posts_tags_m2m_table.columns.tag_id == tag)

    print('Posts with tag', tag)

    for row in result:
        print(row.title)


if __name__ == '__main__':
    Base.metadata.create_all()
    create_users_and_posts_and_tags_and_comments()

    user = 1
    get_posts_by_id_user(user)

    tag = 3
    get_posts_by_tag(tag)

views/posts.py
from flask import Blueprint, render_template, request, redirect, url_for

from models import Post
from models.database import db

post_app = Blueprint("post_app", __name__)

@post_app.route("/", endpoint='posts_list')
def posts_list():
    posts = Post.query.filter_by(deleted=False).all()
    return render_template("posts/post_list.html", posts=posts)

@post_app.route("/<int:post_id>", endpoint='post_detail')
def post_detail(post_id):
    post = Post.get_post_by_id(post_id)

    return render_template(
        "posts/post_detail.html",
        post=post,
    )

@post_app.route("/<int:post_id>/delete", methods=["POST"], endpoint='post_delete')
def post_delete(post_id):
    post = Post.get_post_by_id(post_id)
    post.deleted = True
    db.session.commit()
    return redirect(url_for("post_app.posts_list"))

@post_app.route("/add/", methods=["POST", "GET"], endpoint='add_post')
def post_add():
    if request.method == "GET":
        return render_template("posts/add_post.html")

    post_name = request.form.get("post_name")
    is_new = bool(request.form.get("is-new"))
    post = Post(name=post_name, is_new=is_new)
    db.session.add(post)
    db.session.commit()
    return redirect(url_for("post_app.posts_list"))

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
    <div>
        <p>Hello {{ name }}!</p>
    </div>
</body>
</html>

templates/posts/add_post.html
{% extends 'posts/base.html' %}

{% block title -%}
    Add new post
{%- endblock %}

{% block body %}
    <form method="post">
        <div class="mb-3">
            <label for="input-name" class="form-label">Post name:</label>
            <input id="input-name" name="post_name" type="text" class="form-control">
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" name="is-new" id="check-is-new">
            <label class="form-check-label" for="check-is-new">
                Post is new
            </label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

templates/posts/base.html
<!DOCTYPE html>
<html lang="en" class="page_whole" lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title -%}
            Base
        {%- endblock %}
    </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body class="page">
    <header class="page__header main-header">
        <div class="container">
          <nav class="main-header__navigation main_nav">
            <div class="main_nav__wrapper">
              <a href="#" class="main_nav__toggle-menu">
                <svg id="icon-hamburger" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 25" width="40" height="25">
                  <path d="M38 3H2L0 2V1l2-1h36l1 1v1l-1 1zm0 11H2l-2-1v-1l2-1h36l1 1v1l-1 1zm0 11H2l-2-1v-1l2-1h36l1 1v1l-1 1z">
                  </path>
                </svg>
              </a>

              <ul class="main_nav__menu list">
                <li class="site-list__item site-list__item--active">
                  <a href="{{ url_for('post_app.posts_list') }}">Главная</a>
                </li>
                <li class="site-list__item">
                  <a href="contacts.html">Контакты</a>
                </li>
              </ul>
            </div>
            <a href="#" class="main_nav__logo logo">
              <img class="logo__image" src="{{ url_for('static', filename='img/logo.png') }}" width="50" height="50" alt="Workouts">
            </a>
            <form class="main_nav__search-form search-form" action="https://otus.ru" method="post">
              <label for="search"></label>
              <input class="search-form__input" id="search" aria-label="поиск" type="text" name="key-word" placeholder="Поиск по сайту">
              <button class="search-form__button" type="submit"></button>
            </form>
          </nav>
        </div>
    </header>

    {% block body %}
        <h1>Base body</h1>
    {% endblock %}

   <footer class="page__footer main-footer">
       <div class="container container-row">
          <a class="main-footer__logo logo">
            <img class="logo__image" src="{{ url_for('static', filename='img/logo.png') }}" width="50" height="50" alt="Workouts">
          </a>

          <ul class="main-footer__social social list">
            <li class="social__item">
              <a class="social__link social__link--facebook" href="#"><span class="visually-hidden">Мы в Фейсбуке</span></a>
            </li>
            <li class="social__item">
              <a class="social__link social__link--twitter" href="#"><span class="visually-hidden">Мы в Твитере</span></a>
            </li>
            <li class="social__item">
              <a class="social__link social__link--instagram" href="#"><span class="visually-hidden">Мы в
                Инстаграме</span></a>
            </li>
          </ul>
       </div>
   </footer>
</body>
</html>

templates/posts/post_detail.html
{% extends 'posts/base.html' %}

{% block title -%}
    Post #{{ post.id }}
{%- endblock %}

{% block body %}
    <main class="page__one-block one-block container">
        <section class="one--block__details details">
            <div class="details__image">
                <img src="{{ url_for('static', filename='img/images01.jfif') }}"
                    alt="The Top 10 Benefits of Regular Exercise">
            </div>

            <div class="details__container">
                <h3 class="details__title">
                  {{ post.title -}}
                </h3>

                <p class="details__text">
                  {{ post.text -}}
                </p>
            </div>
        </section>
    </main>
{% endblock %}

templates/posts/post_list.html
{% extends 'posts/base.html' %}

{% block title -%}
    Workouts
{%- endblock %}

{% block body %}
<main class="page__main main container">
    <section class="main__blocks blocks">
        <ul class="blocks__list list list--none">
            {% for post in posts %}
                <li class="blocks__item block">
                    <div class="block__image">
                        <img src="{{ url_for('static', filename='img/images01.jfif') }}"
                          alt="The Top 10 Benefits of Regular Exercise">
                    </div>
                    <div class="block__container">
                        <h3 class="block__title">
                            {{ post.title -}}
                        </h3>
                        <p class="block__text">
                            {{ post.text -}}
                        </p>

                        <a class="block__link button" href="{{ url_for('post_app.post_detail', post_id=post.id)}}">more</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </section>
</main>
{% endblock %}